#!/bin/bash
sudo docker run -d --name postgres -p 5432:5432 postgres
sudo docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 nickstenning/elasticsearch-icu
sudo docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 --hostname rabbit rabbitmq:3-management
#sudo docker run -d --name redis -p 6379:6379 redis
#sudo docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 elasticsearch_v1
#sudo docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 --hostname rabbitmq_v1
#sudo docker run -d --name redis -p 6379:6379 redis_v1
